# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 621)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(800, 621))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 200);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameMain = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameMain.sizePolicy().hasHeightForWidth())
        self.frameMain.setSizePolicy(sizePolicy)
        self.frameMain.setMinimumSize(QtCore.QSize(0, 0))
        self.frameMain.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frameMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMain.setObjectName("frameMain")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameMain)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_data_settings = QtWidgets.QGroupBox(self.frameMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_data_settings.sizePolicy().hasHeightForWidth())
        self.groupBox_data_settings.setSizePolicy(sizePolicy)
        self.groupBox_data_settings.setStyleSheet("")
        self.groupBox_data_settings.setObjectName("groupBox_data_settings")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_data_settings)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frameMonthlyAllowance = QtWidgets.QFrame(self.groupBox_data_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameMonthlyAllowance.sizePolicy().hasHeightForWidth())
        self.frameMonthlyAllowance.setSizePolicy(sizePolicy)
        self.frameMonthlyAllowance.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameMonthlyAllowance.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMonthlyAllowance.setObjectName("frameMonthlyAllowance")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frameMonthlyAllowance)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_monthly_data_allowance_gb = QtWidgets.QHBoxLayout()
        self.horizontalLayout_monthly_data_allowance_gb.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_monthly_data_allowance_gb.setObjectName("horizontalLayout_monthly_data_allowance_gb")
        self.label_monthly_data_allowance_gb = QtWidgets.QLabel(self.frameMonthlyAllowance)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_monthly_data_allowance_gb.sizePolicy().hasHeightForWidth())
        self.label_monthly_data_allowance_gb.setSizePolicy(sizePolicy)
        self.label_monthly_data_allowance_gb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_monthly_data_allowance_gb.setObjectName("label_monthly_data_allowance_gb")
        self.horizontalLayout_monthly_data_allowance_gb.addWidget(self.label_monthly_data_allowance_gb)
        self.spinBox_data_allowance_gb_x_100 = QtWidgets.QSpinBox(self.frameMonthlyAllowance)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_data_allowance_gb_x_100.sizePolicy().hasHeightForWidth())
        self.spinBox_data_allowance_gb_x_100.setSizePolicy(sizePolicy)
        self.spinBox_data_allowance_gb_x_100.setMaximum(9)
        self.spinBox_data_allowance_gb_x_100.setObjectName("spinBox_data_allowance_gb_x_100")
        self.horizontalLayout_monthly_data_allowance_gb.addWidget(self.spinBox_data_allowance_gb_x_100)
        self.spinBox_data_allowance_gb_x_10 = QtWidgets.QSpinBox(self.frameMonthlyAllowance)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_data_allowance_gb_x_10.sizePolicy().hasHeightForWidth())
        self.spinBox_data_allowance_gb_x_10.setSizePolicy(sizePolicy)
        self.spinBox_data_allowance_gb_x_10.setMaximum(9)
        self.spinBox_data_allowance_gb_x_10.setObjectName("spinBox_data_allowance_gb_x_10")
        self.horizontalLayout_monthly_data_allowance_gb.addWidget(self.spinBox_data_allowance_gb_x_10)
        self.spinBox_data_allowance_gb_x_1 = QtWidgets.QSpinBox(self.frameMonthlyAllowance)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_data_allowance_gb_x_1.sizePolicy().hasHeightForWidth())
        self.spinBox_data_allowance_gb_x_1.setSizePolicy(sizePolicy)
        self.spinBox_data_allowance_gb_x_1.setMaximum(9)
        self.spinBox_data_allowance_gb_x_1.setObjectName("spinBox_data_allowance_gb_x_1")
        self.horizontalLayout_monthly_data_allowance_gb.addWidget(self.spinBox_data_allowance_gb_x_1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_monthly_data_allowance_gb)
        self.verticalLayout_11.addWidget(self.frameMonthlyAllowance)
        self.frameDataCapResetDayOfMonth = QtWidgets.QFrame(self.groupBox_data_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameDataCapResetDayOfMonth.sizePolicy().hasHeightForWidth())
        self.frameDataCapResetDayOfMonth.setSizePolicy(sizePolicy)
        self.frameDataCapResetDayOfMonth.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameDataCapResetDayOfMonth.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDataCapResetDayOfMonth.setObjectName("frameDataCapResetDayOfMonth")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frameDataCapResetDayOfMonth)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_data_cap_reset = QtWidgets.QHBoxLayout()
        self.horizontalLayout_data_cap_reset.setObjectName("horizontalLayout_data_cap_reset")
        self.label_day_of_month_data_cap_reset = QtWidgets.QLabel(self.frameDataCapResetDayOfMonth)
        self.label_day_of_month_data_cap_reset.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_day_of_month_data_cap_reset.setObjectName("label_day_of_month_data_cap_reset")
        self.horizontalLayout_data_cap_reset.addWidget(self.label_day_of_month_data_cap_reset)
        self.label_day_of_month_data_cap_reset_live_value = QtWidgets.QLabel(self.frameDataCapResetDayOfMonth)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_day_of_month_data_cap_reset_live_value.sizePolicy().hasHeightForWidth())
        self.label_day_of_month_data_cap_reset_live_value.setSizePolicy(sizePolicy)
        self.label_day_of_month_data_cap_reset_live_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_day_of_month_data_cap_reset_live_value.setObjectName("label_day_of_month_data_cap_reset_live_value")
        self.horizontalLayout_data_cap_reset.addWidget(self.label_day_of_month_data_cap_reset_live_value)
        self.horizontalScrollBar_day_of_month_data_cap_reset = QtWidgets.QScrollBar(self.frameDataCapResetDayOfMonth)
        self.horizontalScrollBar_day_of_month_data_cap_reset.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.horizontalScrollBar_day_of_month_data_cap_reset.setMinimum(1)
        self.horizontalScrollBar_day_of_month_data_cap_reset.setMaximum(31)
        self.horizontalScrollBar_day_of_month_data_cap_reset.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_day_of_month_data_cap_reset.setInvertedAppearance(False)
        self.horizontalScrollBar_day_of_month_data_cap_reset.setObjectName("horizontalScrollBar_day_of_month_data_cap_reset")
        self.horizontalLayout_data_cap_reset.addWidget(self.horizontalScrollBar_day_of_month_data_cap_reset)
        self.verticalLayout_10.addLayout(self.horizontalLayout_data_cap_reset)
        self.verticalLayout_11.addWidget(self.frameDataCapResetDayOfMonth)
        self.frameDataUsage = QtWidgets.QFrame(self.groupBox_data_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameDataUsage.sizePolicy().hasHeightForWidth())
        self.frameDataUsage.setSizePolicy(sizePolicy)
        self.frameDataUsage.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameDataUsage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDataUsage.setObjectName("frameDataUsage")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frameDataUsage)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayoutDataUsage = QtWidgets.QHBoxLayout()
        self.horizontalLayoutDataUsage.setObjectName("horizontalLayoutDataUsage")
        self.label_current_data_usage = QtWidgets.QLabel(self.frameDataUsage)
        self.label_current_data_usage.setObjectName("label_current_data_usage")
        self.horizontalLayoutDataUsage.addWidget(self.label_current_data_usage)
        self.pushButton_reset_data_usage = QtWidgets.QPushButton(self.frameDataUsage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_reset_data_usage.sizePolicy().hasHeightForWidth())
        self.pushButton_reset_data_usage.setSizePolicy(sizePolicy)
        self.pushButton_reset_data_usage.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.pushButton_reset_data_usage.setObjectName("pushButton_reset_data_usage")
        self.horizontalLayoutDataUsage.addWidget(self.pushButton_reset_data_usage)
        self.label_data_usage_value = QtWidgets.QLabel(self.frameDataUsage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_usage_value.sizePolicy().hasHeightForWidth())
        self.label_data_usage_value.setSizePolicy(sizePolicy)
        self.label_data_usage_value.setMinimumSize(QtCore.QSize(100, 0))
        self.label_data_usage_value.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_data_usage_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_data_usage_value.setObjectName("label_data_usage_value")
        self.horizontalLayoutDataUsage.addWidget(self.label_data_usage_value)
        self.labelDataUsageKb = QtWidgets.QLabel(self.frameDataUsage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDataUsageKb.sizePolicy().hasHeightForWidth())
        self.labelDataUsageKb.setSizePolicy(sizePolicy)
        self.labelDataUsageKb.setObjectName("labelDataUsageKb")
        self.horizontalLayoutDataUsage.addWidget(self.labelDataUsageKb)
        self.verticalLayout_12.addLayout(self.horizontalLayoutDataUsage)
        self.verticalLayout_11.addWidget(self.frameDataUsage)
        self.frameUploadStopMargin = QtWidgets.QFrame(self.groupBox_data_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameUploadStopMargin.sizePolicy().hasHeightForWidth())
        self.frameUploadStopMargin.setSizePolicy(sizePolicy)
        self.frameUploadStopMargin.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameUploadStopMargin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameUploadStopMargin.setObjectName("frameUploadStopMargin")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frameUploadStopMargin)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_upload_stop_margin = QtWidgets.QHBoxLayout()
        self.horizontalLayout_upload_stop_margin.setObjectName("horizontalLayout_upload_stop_margin")
        self.label_upload_stop_margin_blocks_32MB = QtWidgets.QLabel(self.frameUploadStopMargin)
        self.label_upload_stop_margin_blocks_32MB.setObjectName("label_upload_stop_margin_blocks_32MB")
        self.horizontalLayout_upload_stop_margin.addWidget(self.label_upload_stop_margin_blocks_32MB)
        self.spinBox_upload_stop_margin_MB = QtWidgets.QSpinBox(self.frameUploadStopMargin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_upload_stop_margin_MB.sizePolicy().hasHeightForWidth())
        self.spinBox_upload_stop_margin_MB.setSizePolicy(sizePolicy)
        self.spinBox_upload_stop_margin_MB.setMinimum(32)
        self.spinBox_upload_stop_margin_MB.setMaximum(1024)
        self.spinBox_upload_stop_margin_MB.setSingleStep(32)
        self.spinBox_upload_stop_margin_MB.setObjectName("spinBox_upload_stop_margin_MB")
        self.horizontalLayout_upload_stop_margin.addWidget(self.spinBox_upload_stop_margin_MB)
        self.verticalLayout_13.addLayout(self.horizontalLayout_upload_stop_margin)
        self.verticalLayout_11.addWidget(self.frameUploadStopMargin)
        self.verticalLayout.addWidget(self.groupBox_data_settings)
        self.groupBoxPictureUploadConfiguration = QtWidgets.QGroupBox(self.frameMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPictureUploadConfiguration.sizePolicy().hasHeightForWidth())
        self.groupBoxPictureUploadConfiguration.setSizePolicy(sizePolicy)
        self.groupBoxPictureUploadConfiguration.setObjectName("groupBoxPictureUploadConfiguration")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBoxPictureUploadConfiguration)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.framePictureUploadConfiguration = QtWidgets.QFrame(self.groupBoxPictureUploadConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePictureUploadConfiguration.sizePolicy().hasHeightForWidth())
        self.framePictureUploadConfiguration.setSizePolicy(sizePolicy)
        self.framePictureUploadConfiguration.setFrameShape(QtWidgets.QFrame.Panel)
        self.framePictureUploadConfiguration.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePictureUploadConfiguration.setObjectName("framePictureUploadConfiguration")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.framePictureUploadConfiguration)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayoutCameraConfiguration = QtWidgets.QHBoxLayout()
        self.horizontalLayoutCameraConfiguration.setObjectName("horizontalLayoutCameraConfiguration")
        self.verticalLayoutCameraConfiguration = QtWidgets.QVBoxLayout()
        self.verticalLayoutCameraConfiguration.setObjectName("verticalLayoutCameraConfiguration")
        self.horizontalLayoutCam1 = QtWidgets.QHBoxLayout()
        self.horizontalLayoutCam1.setObjectName("horizontalLayoutCam1")
        self.checkBoxCam1 = QtWidgets.QCheckBox(self.framePictureUploadConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxCam1.sizePolicy().hasHeightForWidth())
        self.checkBoxCam1.setSizePolicy(sizePolicy)
        self.checkBoxCam1.setStyleSheet("background-color: rgba(255, 200, 200, 200);")
        self.checkBoxCam1.setObjectName("checkBoxCam1")
        self.horizontalLayoutCam1.addWidget(self.checkBoxCam1)
        self.verticalLayoutCameraConfiguration.addLayout(self.horizontalLayoutCam1)
        self.horizontalLayoutCam2 = QtWidgets.QHBoxLayout()
        self.horizontalLayoutCam2.setObjectName("horizontalLayoutCam2")
        self.checkBoxCam2 = QtWidgets.QCheckBox(self.framePictureUploadConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxCam2.sizePolicy().hasHeightForWidth())
        self.checkBoxCam2.setSizePolicy(sizePolicy)
        self.checkBoxCam2.setStyleSheet("background-color: rgba(255, 200, 200, 200);")
        self.checkBoxCam2.setObjectName("checkBoxCam2")
        self.horizontalLayoutCam2.addWidget(self.checkBoxCam2)
        self.verticalLayoutCameraConfiguration.addLayout(self.horizontalLayoutCam2)
        self.horizontalLayoutCam3 = QtWidgets.QHBoxLayout()
        self.horizontalLayoutCam3.setObjectName("horizontalLayoutCam3")
        self.checkBoxCam3 = QtWidgets.QCheckBox(self.framePictureUploadConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxCam3.sizePolicy().hasHeightForWidth())
        self.checkBoxCam3.setSizePolicy(sizePolicy)
        self.checkBoxCam3.setStyleSheet("background-color: rgba(255, 200, 200, 200);")
        self.checkBoxCam3.setObjectName("checkBoxCam3")
        self.horizontalLayoutCam3.addWidget(self.checkBoxCam3)
        self.verticalLayoutCameraConfiguration.addLayout(self.horizontalLayoutCam3)
        self.horizontalLayoutCam4 = QtWidgets.QHBoxLayout()
        self.horizontalLayoutCam4.setObjectName("horizontalLayoutCam4")
        self.checkBoxCam4 = QtWidgets.QCheckBox(self.framePictureUploadConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxCam4.sizePolicy().hasHeightForWidth())
        self.checkBoxCam4.setSizePolicy(sizePolicy)
        self.checkBoxCam4.setStyleSheet("background-color: rgba(255, 200, 200, 200);")
        self.checkBoxCam4.setObjectName("checkBoxCam4")
        self.horizontalLayoutCam4.addWidget(self.checkBoxCam4)
        self.verticalLayoutCameraConfiguration.addLayout(self.horizontalLayoutCam4)
        self.horizontalLayoutCam5 = QtWidgets.QHBoxLayout()
        self.horizontalLayoutCam5.setObjectName("horizontalLayoutCam5")
        self.checkBoxCam5 = QtWidgets.QCheckBox(self.framePictureUploadConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxCam5.sizePolicy().hasHeightForWidth())
        self.checkBoxCam5.setSizePolicy(sizePolicy)
        self.checkBoxCam5.setStyleSheet("background-color: rgba(255, 200, 200, 200);")
        self.checkBoxCam5.setObjectName("checkBoxCam5")
        self.horizontalLayoutCam5.addWidget(self.checkBoxCam5)
        self.verticalLayoutCameraConfiguration.addLayout(self.horizontalLayoutCam5)
        self.horizontalLayoutCam6 = QtWidgets.QHBoxLayout()
        self.horizontalLayoutCam6.setObjectName("horizontalLayoutCam6")
        self.checkBoxCam6 = QtWidgets.QCheckBox(self.framePictureUploadConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxCam6.sizePolicy().hasHeightForWidth())
        self.checkBoxCam6.setSizePolicy(sizePolicy)
        self.checkBoxCam6.setStyleSheet("background-color: rgba(255, 200, 200, 200);")
        self.checkBoxCam6.setObjectName("checkBoxCam6")
        self.horizontalLayoutCam6.addWidget(self.checkBoxCam6)
        self.verticalLayoutCameraConfiguration.addLayout(self.horizontalLayoutCam6)
        self.horizontalLayoutCam7 = QtWidgets.QHBoxLayout()
        self.horizontalLayoutCam7.setObjectName("horizontalLayoutCam7")
        self.checkBoxCam7 = QtWidgets.QCheckBox(self.framePictureUploadConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxCam7.sizePolicy().hasHeightForWidth())
        self.checkBoxCam7.setSizePolicy(sizePolicy)
        self.checkBoxCam7.setStyleSheet("background-color: rgba(255, 200, 200, 200);")
        self.checkBoxCam7.setObjectName("checkBoxCam7")
        self.horizontalLayoutCam7.addWidget(self.checkBoxCam7)
        self.verticalLayoutCameraConfiguration.addLayout(self.horizontalLayoutCam7)
        self.horizontalLayoutCam8 = QtWidgets.QHBoxLayout()
        self.horizontalLayoutCam8.setObjectName("horizontalLayoutCam8")
        self.checkBoxCam8 = QtWidgets.QCheckBox(self.framePictureUploadConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxCam8.sizePolicy().hasHeightForWidth())
        self.checkBoxCam8.setSizePolicy(sizePolicy)
        self.checkBoxCam8.setStyleSheet("background-color: rgba(255, 200, 200, 200);")
        self.checkBoxCam8.setObjectName("checkBoxCam8")
        self.horizontalLayoutCam8.addWidget(self.checkBoxCam8)
        self.verticalLayoutCameraConfiguration.addLayout(self.horizontalLayoutCam8)
        self.horizontalLayoutCameraConfiguration.addLayout(self.verticalLayoutCameraConfiguration)
        self.pushButtonConfigureCameras = QtWidgets.QPushButton(self.framePictureUploadConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonConfigureCameras.sizePolicy().hasHeightForWidth())
        self.pushButtonConfigureCameras.setSizePolicy(sizePolicy)
        self.pushButtonConfigureCameras.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.pushButtonConfigureCameras.setObjectName("pushButtonConfigureCameras")
        self.horizontalLayoutCameraConfiguration.addWidget(self.pushButtonConfigureCameras)
        self.verticalLayout_3.addLayout(self.horizontalLayoutCameraConfiguration)
        self.verticalLayout_5.addWidget(self.framePictureUploadConfiguration)
        self.verticalLayout.addWidget(self.groupBoxPictureUploadConfiguration)
        self.groupBox_misc = QtWidgets.QGroupBox(self.frameMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_misc.sizePolicy().hasHeightForWidth())
        self.groupBox_misc.setSizePolicy(sizePolicy)
        self.groupBox_misc.setObjectName("groupBox_misc")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_misc)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frameMisc = QtWidgets.QFrame(self.groupBox_misc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameMisc.sizePolicy().hasHeightForWidth())
        self.frameMisc.setSizePolicy(sizePolicy)
        self.frameMisc.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameMisc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMisc.setObjectName("frameMisc")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frameMisc)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_ffmpeg_timeout = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ffmpeg_timeout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_ffmpeg_timeout.setObjectName("horizontalLayout_ffmpeg_timeout")
        self.label_ffmpeg_timeout = QtWidgets.QLabel(self.frameMisc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ffmpeg_timeout.sizePolicy().hasHeightForWidth())
        self.label_ffmpeg_timeout.setSizePolicy(sizePolicy)
        self.label_ffmpeg_timeout.setObjectName("label_ffmpeg_timeout")
        self.horizontalLayout_ffmpeg_timeout.addWidget(self.label_ffmpeg_timeout)
        self.spinBox_ffmpeg_timeout_s = QtWidgets.QSpinBox(self.frameMisc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_ffmpeg_timeout_s.sizePolicy().hasHeightForWidth())
        self.spinBox_ffmpeg_timeout_s.setSizePolicy(sizePolicy)
        self.spinBox_ffmpeg_timeout_s.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_ffmpeg_timeout_s.setMinimum(5)
        self.spinBox_ffmpeg_timeout_s.setMaximum(25)
        self.spinBox_ffmpeg_timeout_s.setProperty("value", 10)
        self.spinBox_ffmpeg_timeout_s.setObjectName("spinBox_ffmpeg_timeout_s")
        self.horizontalLayout_ffmpeg_timeout.addWidget(self.spinBox_ffmpeg_timeout_s)
        self.verticalLayout_7.addLayout(self.horizontalLayout_ffmpeg_timeout)
        self.verticalLayout_6.addWidget(self.frameMisc)
        self.verticalLayout.addWidget(self.groupBox_misc)
        self.horizontalLayout_ok_cancel = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ok_cancel.setContentsMargins(0, 9, -1, -1)
        self.horizontalLayout_ok_cancel.setSpacing(6)
        self.horizontalLayout_ok_cancel.setObjectName("horizontalLayout_ok_cancel")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_ok_cancel.addItem(spacerItem)
        self.pushButton_reload_config_file = QtWidgets.QPushButton(self.frameMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_reload_config_file.sizePolicy().hasHeightForWidth())
        self.pushButton_reload_config_file.setSizePolicy(sizePolicy)
        self.pushButton_reload_config_file.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.pushButton_reload_config_file.setObjectName("pushButton_reload_config_file")
        self.horizontalLayout_ok_cancel.addWidget(self.pushButton_reload_config_file)
        self.pushButtonApply = QtWidgets.QPushButton(self.frameMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonApply.sizePolicy().hasHeightForWidth())
        self.pushButtonApply.setSizePolicy(sizePolicy)
        self.pushButtonApply.setMinimumSize(QtCore.QSize(128, 16))
        self.pushButtonApply.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.pushButtonApply.setFlat(False)
        self.pushButtonApply.setObjectName("pushButtonApply")
        self.horizontalLayout_ok_cancel.addWidget(self.pushButtonApply)
        self.pushButtonClose = QtWidgets.QPushButton(self.frameMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonClose.sizePolicy().hasHeightForWidth())
        self.pushButtonClose.setSizePolicy(sizePolicy)
        self.pushButtonClose.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.horizontalLayout_ok_cancel.addWidget(self.pushButtonClose)
        self.verticalLayout.addLayout(self.horizontalLayout_ok_cancel)
        self.verticalLayout_2.addWidget(self.frameMain)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Watch Out! Configurator"))
        self.groupBox_data_settings.setTitle(_translate("MainWindow", "Data Settings"))
        self.label_monthly_data_allowance_gb.setText(_translate("MainWindow", "Monthly Data Allowance (100\'s, 10\'s, units of GB)"))
        self.label_day_of_month_data_cap_reset.setText(_translate("MainWindow", "Day of the month data cap is reset"))
        self.label_day_of_month_data_cap_reset_live_value.setText(_translate("MainWindow", "1"))
        self.label_current_data_usage.setText(_translate("MainWindow", "Current data usage"))
        self.pushButton_reset_data_usage.setText(_translate("MainWindow", "Reset Data Usage"))
        self.label_data_usage_value.setText(_translate("MainWindow", "0"))
        self.labelDataUsageKb.setText(_translate("MainWindow", "KB"))
        self.label_upload_stop_margin_blocks_32MB.setText(_translate("MainWindow", "Stop uploading pictures within this limit of reaching data CAP (MB)"))
        self.groupBoxPictureUploadConfiguration.setTitle(_translate("MainWindow", "Picture Upload Configuration"))
        self.checkBoxCam1.setText(_translate("MainWindow", "Camera 1"))
        self.checkBoxCam2.setText(_translate("MainWindow", "Camera 2"))
        self.checkBoxCam3.setText(_translate("MainWindow", "Camera 3"))
        self.checkBoxCam4.setText(_translate("MainWindow", "Camera 4"))
        self.checkBoxCam5.setText(_translate("MainWindow", "Camera 5"))
        self.checkBoxCam6.setText(_translate("MainWindow", "Camera 6"))
        self.checkBoxCam7.setText(_translate("MainWindow", "Camera 7"))
        self.checkBoxCam8.setText(_translate("MainWindow", "Camera 8"))
        self.pushButtonConfigureCameras.setText(_translate("MainWindow", "Configure Selected\n"
"Cameras"))
        self.groupBox_misc.setTitle(_translate("MainWindow", "Misc Settings"))
        self.label_ffmpeg_timeout.setText(_translate("MainWindow", "FFMPEG timeout (seconds, min 5, max 25)"))
        self.pushButton_reload_config_file.setText(_translate("MainWindow", "Reload Config File"))
        self.pushButtonApply.setText(_translate("MainWindow", "Apply Configuration"))
        self.pushButtonClose.setText(_translate("MainWindow", "Close"))

